server:
  port: 8083

spring:
  main:
    banner-mode: off
    logging:
      level:
        org:
          springframework:
            data:
              r2dbc: DEBUG
    server:
      error:
        include-stacktrace: on_param
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/cashnow?schema=anime
    username: postgres
    password: postgres
