server:
  port: 8083

spring:
  main:
    banner-mode: off
    logging:
      level:
        org:
          springframework:
            data:
              r2dbc: DEBUG
    server:
      error:
        include-stacktrace: on_param
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/cashnow?schema=anime
    username: postgres
    password: postgres


jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a17dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte
